#!/bin/bash
dusty77;dusty77;dusty77
make -s clean
make -s size=20
dusty77;dusty77;dusty77
make -s clean
make -s size=30
dusty77;dusty77;dusty77
make -s clean
make -s size=40
dusty77;dusty77;dusty77
make -s clean
make -s size=50
dusty77;dusty77;dusty77
make -s clean
make -s size=60
dusty77;dusty77;dusty77
make -s clean
make -s size=70
dusty77;dusty77;dusty77
make -s clean
make -s size=80
dusty77;dusty77;dusty77
make -s clean
make -s size=90
dusty77;dusty77;dusty77
make -s clean
make -s size=100
