#!/usr/bin/bash
make -s 
dusty77;dusty77;dusty77
make -s clean
make -s size=25
dusty77;dusty77;dusty77
make -s clean
make -s size=30
dusty77;dusty77;dusty77
make -s clean
make -s size=40
dusty77;dusty77;dusty77
make -s clean
make -s size=50
dusty77;dusty77;dusty77
make -s clean

