#!/bin/bash
dusty90;dusty90;dusty90
make -s clean
make -s size=20
dusty90;dusty90;dusty90
make -s clean
make -s size=30
dusty90;dusty90;dusty90
make -s clean
make -s size=40
dusty90;dusty90;dusty90
make -s clean
make -s size=50
dusty90;dusty90;dusty90
make -s clean
make -s size=60
dusty90;dusty90;dusty90
make -s clean
make -s size=70
dusty90;dusty90;dusty90
make -s clean
make -s size=80
dusty90;dusty90;dusty90
make -s clean
make -s size=90
dusty90;dusty90;dusty90
make -s clean
make -s size=100
