#!/bin/bash
make -s
make run
make -s clean
make -s size=30
make run
make -s clean
make -s size=40
make run
make -s clean
make -s size=50
make run
make -s clean
make -s size=60
make run
make -s clean
make -s size=70
make run
make -s clean
make -s size=80
make run
make -s clean
make -s size=90
make run
